# ==========================================
# MATPLOTLIB BACKEND FIX (MUST BE FIRST)
# ==========================================
import matplotlib
matplotlib.use("Agg")   # NO GUI backend (Flask safe)

# ==========================================
# STANDARD IMPORTS
# ==========================================
import numpy as np
import pandas as pd
import os
import smtplib
from scipy.signal import butter, filtfilt, find_peaks
from tensorflow.keras.models import load_model
import matplotlib.pyplot as plt
from email.message import EmailMessage
from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas
from email_config import EMAIL_ADDRESS, EMAIL_PASSWORD, SMTP_SERVER, SMTP_PORT

# ==========================================
# LOAD MODEL
# ==========================================
model = load_model("ecg_cnn_lstm_model.h5")

FS = 360
WINDOW = 90

# ==========================================
# SIGNAL PROCESSING
# ==========================================
def bandpass_filter(sig, fs=FS, low=0.5, high=40):
    nyq = 0.5 * fs
    b, a = butter(1, [low/nyq, high/nyq], btype="band")
    return filtfilt(b, a, sig)

# ==========================================
# ECG PREDICTION
# ==========================================
def predict_ecg_csv(csv_path):
    data = pd.read_csv(csv_path)

    if "ecg" not in data.columns:
        raise ValueError("CSV must contain 'ecg' column")

    signal = data["ecg"].values.astype(float)
    filtered = bandpass_filter(signal)

    peaks, _ = find_peaks(filtered, distance=150, height=0.3)

    bpm = int(60 / np.mean(np.diff(peaks) / FS)) if len(peaks) > 1 else 0

    if bpm < 60:
        hr_status = "Bradycardia"
    elif bpm > 100:
        hr_status = "Tachycardia"
    else:
        hr_status = "Normal"

    preds = []
    for p in peaks:
        if p-WINDOW >= 0 and p+WINDOW < len(filtered):
            beat = filtered[p-WINDOW:p+WINDOW].reshape(1, 180, 1)
            preds.append(model.predict(beat, verbose=0)[0][0])

    avg_prob = float(np.mean(preds)) if preds else 0.0

    if avg_prob > 0.7:
        label, risk = "ABNORMAL", "HIGH RISK"
    elif avg_prob > 0.4:
        label, risk = "ABNORMAL", "MODERATE RISK"
    else:
        label, risk = "NORMAL", "LOW RISK"

    # ---------- SAVE ECG IMAGE FOR PDF ----------
    os.makedirs("static", exist_ok=True)
    plt.ioff()
    plt.figure(figsize=(10, 4))
    plt.plot(filtered[:2000])
    plt.scatter(
        peaks[peaks < 2000],
        filtered[peaks[peaks < 2000]],
        color="red"
    )
    plt.title(f"ECG Signal ({label})")
    plt.savefig("static/ecg_plot.png")
    plt.close()

    return label, avg_prob, risk, bpm, hr_status

# ==========================================
# PDF GENERATION
# ==========================================
def generate_pdf(patient, result, probability, risk, bpm, hr_status):
    os.makedirs("reports", exist_ok=True)
    pdf_path = "reports/ecg_report.pdf"

    c = canvas.Canvas(pdf_path, pagesize=A4)
    width, height = A4

    c.setFont("Helvetica-Bold", 18)
    c.drawString(50, height - 50, "ECG ARRHYTHMIA REPORT")

    c.setFont("Helvetica", 12)
    y = height - 100

    for key, value in patient.items():
        c.drawString(50, y, f"{key.capitalize()}: {value}")
        y -= 20

    c.drawString(50, y, f"Diagnosis: {result}")
    y -= 20
    c.drawString(50, y, f"Risk Level: {risk}")
    y -= 20
    c.drawString(50, y, f"Probability: {round(probability, 3)}")
    y -= 20
    c.drawString(50, y, f"Heart Rate: {bpm} BPM ({hr_status})")

    c.drawImage("static/ecg_plot.png", 50, y - 260, width=500, height=200)

    c.setFont("Helvetica-Oblique", 11)
    c.drawString(
        50, 60,
        "AI-assisted diagnosis. Final decision should be made by a cardiologist."
    )

    c.save()
    return pdf_path

# ==========================================
# EMAIL SENDING
# ==========================================
def send_report_email(
    doctor_email,
    patient_name,
    age,
    gender,
    risk,
    bpm,
    probability,
    pdf_path
):
    msg = EmailMessage()
    msg["From"] = EMAIL_ADDRESS
    msg["To"] = doctor_email
    msg["Subject"] = f"ECG Report – {patient_name}"

    msg.set_content(f"""
AI ECG ARRHYTHMIA REPORT

Patient Name: {patient_name}
Age: {age}
Gender: {gender}

Risk Level: {risk}
Heart Rate: {bpm} BPM
Probability: {probability:.2%}

This report is generated by the AI Cardiac Diagnostic System.
""")

    with open(pdf_path, "rb") as f:
        msg.add_attachment(
            f.read(),
            maintype="application",
            subtype="pdf",
            filename="ECG_Report.pdf"
        )

    with smtplib.SMTP(SMTP_SERVER, SMTP_PORT) as server:
        server.starttls()
        server.login(EMAIL_ADDRESS, EMAIL_PASSWORD)
        server.send_message(msg)
